name: 'Crear tag'
description: 'Action para crear el tag personalizado para la imágen'
inputs: 
  user:
    description: 'nombre de usuario en docker'
    required: true
  etiqueta:
    description: 'añadir a la etiqueta snapshot o no'
    required: true
outputs:
  tag:
    description: 'tag final de la imagen'
    value: ${{ steps.generar-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: "Obtener la versión"
      run: |
        echo "version=$(jq -r '.version' ./package.json)" >> $GITHUB_ENV
        echo "image=$(jq -r '.name' ./package.json)" >> $GITHUB_ENV
      shell: bash
    - name: Crear el tag
      id: generar-tag
      run: echo "tag=${{ inputs.user }}/${{ env.image }}:${{ env.version }}${{ inputs.etiqueta }}" >> $GITHUB_OUTPUT
      shell: bash
