name: ci
on:
  workflow_call:
    inputs:
      entorno:
        required: true
        type: string
      etiqueta:
        required: true
        type: string
    outputs:
      tag:
        value: ${{ jobs.build.outputs.tag }}

jobs:
  test: 
    if: ${{ inputs.entorno == 'production' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.entorno }}
    container:
      image: node:latest
    steps:
      - run: echo "SIMULACIÓN DE TESTS"
      - uses: actions/checkout@v4
      - run: echo npm install
      - run: echo instalando...
      - run: sleep 2
      - run: echo npm run test
      - run: echo realizando tests...
      - run: sleep 2
      - run: echo EXITO

  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.entorno }}
    needs: test
    if: ${{ always() && !failure()}}
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Obtener tag
        id: tag
        uses: ./.github/actions/getTag
        with:
          user: ${{ vars.DOCKER_USERNAME }}
          etiqueta: ${{ inputs.etiqueta }}

      - name: login en docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir a docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.tag }}


